services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${MNT_DATA}/Configs/Mosquitto:/mosquitto/config
      - ${MNT_METRIC_DATA}/Mosquitto/data:/mosquitto/data
      - ${MNT_METRIC_DATA}/Mosquitto/log:/mosquitto/log
    restart: always

  mqtt-exporter:
    image: kpetrem/mqtt-exporter
    container_name: prometheus-mqtt-exporter
    ports:
      - 9000:9000
    environment:
      - MQTT_ADDRESS=${MQTT_ADDRESS}
      - PROMETHEUS_PREFIX=sensor_
      - TOPIC_LABEL=sensor
      - ESPHOME_TOPIC_PREFIXES=weather
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    restart: always