esphome:
  name: weather
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local
  fast_connect: true
  manual_ip:
    static_ip: 192.168.88.40
    gateway: 192.168.88.88
    subnet: 255.255.255.0

# Enable logging
logger:

# MQTT Client Configuration
mqtt:
  broker: "192.168.88.88"
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false # push data only

# OTA Updates
ota:
  - platform: esphome
    password: !secret ota_password

# Deep Sleep Configuration
deep_sleep:
  run_duration: 60s
  sleep_duration: 15min

# I2C Configuration for BME280
i2c:
  sda: D2
  scl: D1
  scan: True

# BME280 Sensor Configuration
sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      id: temp
    humidity:
      name: "BME280 Humidity"
      id: humidity
    pressure:
      name: "BME280 Pressure"
      id: pressure
    address: 0x76
    update_interval: 60s

  # Battery voltage
  - platform: adc
    pin: A0
    name: "Battery Voltage"
    id: battery
    update_interval: 60s
    filters:
      - multiply: 5.18

  # Wifi signal
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: wifi_db
    update_interval: 60s
