esphome:
  name: weather
  on_boot:
    - priority: 600
      then:
        - output.turn_on: bme280_power
        - delay: 100ms
        - component.update: battery
        - component.update: bme280
    - priority: -110
      then:
        - component.update: wifidb
  on_shutdown:
    then:
      - output.turn_off: bme280_power

esp8266:
  board: d1_mini

# Enable WIFI with a custom IP to speed up connection
wifi:
  # use_address: weather.local
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: LIGHT
  manual_ip:
    static_ip: 192.168.88.52
    gateway: 192.168.88.1
    subnet: 255.255.255.0

logger:
  level: ERROR

# MQTT Client Configuration
mqtt:
  broker: "192.168.88.24"
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false # push data only

# OTA Updates
ota:
  - platform: esphome
    password: !secret ota_password

# Deep Sleep Configuration
deep_sleep:
  run_duration: 5s
  sleep_duration: 10min

# I2C Configuration for BME280
i2c:
  sda: D2
  scl: D1
  scan: False

sensor:
  - platform: bme280_i2c
    id: bme280
    temperature:
      name: "BME280 Temperature"
      id: temp
    humidity:
      name: "BME280 Humidity"
      id: humidity
    pressure:
      name: "BME280 Pressure"
      id: pressure
    address: 0x76
    update_interval: never

  - platform: adc
    pin: A0
    name: "Battery Voltage"
    id: battery
    update_interval: never
    accuracy_decimals: 3
    filters:
      - multiply: 5.28

  - platform: wifi_signal
    id: wifidb
    name: "WiFi Signal"
    update_interval: never

status_led:
  pin:
    number: GPIO2
    inverted: true

output:
  - platform: gpio
    pin: D5
    id: bme280_power
