esphome:
  name: outdoor-weather
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# MQTT Client Configuration
mqtt:
  broker: '192.168.88.88'
  username: !secret mqtt_username
  password: !secret mqtt_password

# OTA Updates
ota:
  - platform: esphome
    password: !secret ota_password

# Deep Sleep Configuration
deep_sleep:
  run_duration: 60s
  sleep_duration: 30min

# I2C Configuration for BME280
i2c:
  sda: D2
  scl: D1
  scan: True

# BME280 Sensor Configuration
sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      id: bme_temp
    humidity:
      name: "BME280 Humidity"
      id: bme_humidity
    pressure:
      name: "BME280 Pressure"
      id: bme_pressure
    address: 0x76
    update_interval: 60s
    on_value:
      - mqtt.publish:
          topic: 'weather_station/temperature'
          payload: !lambda 'return to_string(x);'
      - mqtt.publish:
          topic: 'weather_station/humidity'
          payload: !lambda 'return to_string(x);'
      - mqtt.publish:
          topic: 'weather_station/pressure'
          payload: !lambda 'return to_string(x);' 

# Battery voltage
  - platform: adc
    pin: A0
    name: "Battery Voltage"
    id: battery_voltage
    update_interval: 60s
    attenuation: 11db
    filters:
      - multiply: 3.3
    on_value:
      - mqtt.publish:
          topic: 'weather_station/battery_voltage'
          payload: !lambda 'return to_string(x);'