esphome:
  name: weather
  on_boot:
    priority: 600
    then:
      - output.turn_on: bme280_power
      - delay: 500ms
      - component.update: bme280
      - delay: 1s
      - output.turn_off: bme280_power
      - component.update: battery
      - component.update: wifi_db

esp8266:
  board: d1_mini

# Enable WIFI with a custom IP to speed up connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local
  fast_connect: true
  # power_save_mode: LIGHT
  manual_ip:
    static_ip: 192.168.88.40
    gateway: 192.168.88.88
    subnet: 255.255.255.0

logger:
  level: WARN

# MQTT Client Configuration
mqtt:
  broker: "192.168.88.88"
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false # push data only
  log_topic: weather/log
  birth_message:
    topic: weather/sensor/status/state
    payload: 1 # online
  will_message:
    topic: weather/sensor/status/state
    payload: 0 # offline

# OTA Updates
ota:
  - platform: esphome
    password: !secret ota_password

# Deep Sleep Configuration
deep_sleep:
  run_duration: 10s
  sleep_duration: 15min

# I2C Configuration for BME280
i2c:
  sda: D2
  scl: D1
  scan: False

sensor:
  - platform: bme280_i2c
    id: bme280
    temperature:
      name: "BME280 Temperature"
      id: temp
    humidity:
      name: "BME280 Humidity"
      id: humidity
    pressure:
      name: "BME280 Pressure"
      id: pressure
    address: 0x76
    update_interval: never

  - platform: adc
    pin: A0
    name: "Battery Voltage"
    id: battery
    update_interval: never
    accuracy_decimals: 3
    filters:
      - multiply: 5.363

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: wifi_db
    update_interval: never

  - platform: uptime
    name: "ESP Uptime"
    type: seconds
    accuracy_decimals: 3

binary_sensor:
  - platform: status
    name: "ESP Status"

status_led:
  pin:
    number: GPIO2
    inverted: true

output:
  - platform: gpio
    pin: D5
    id: bme280_power
